Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/999/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Forbidden: /post/1/
Internal Server Error: /post/999/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_13/solved/django_questions/library/views.py", line 9, in blog_post_detail
    post = BlogPost.objects.get(id=post_id)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
library.models.BlogPost.DoesNotExist: BlogPost matching query does not exist.
Internal Server Error: /post/999/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_13/solved/django_questions/library/views.py", line 9, in blog_post_detail
    post = BlogPost.objects.get(id=post_id)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
library.models.BlogPost.DoesNotExist: BlogPost matching query does not exist.
Internal Server Error: /post/999/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_13/solved/django_questions/library/views.py", line 9, in blog_post_detail
    post = BlogPost.objects.get(id=post_id)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
library.models.BlogPost.DoesNotExist: BlogPost matching query does not exist.
Internal Server Error: /post/999/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_13/solved/django_questions/library/views.py", line 9, in blog_post_detail
    post = BlogPost.objects.get(id=post_id)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
library.models.BlogPost.DoesNotExist: BlogPost matching query does not exist.
Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 38, in register
    if form.clean_email():
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 20, in clean_email
    email = self.cleaned_data['email']
AttributeError: 'RegistrationForm' object has no attribute 'cleaned_data'
Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 38, in register
    if form.clean_email():
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 20, in clean_email
    email = self.cleaned_data['email']
AttributeError: 'RegistrationForm' object has no attribute 'cleaned_data'
Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 35, in register
    if form.clean_email():
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 20, in clean_email
    email = self.cleaned_data['email']
AttributeError: 'RegistrationForm' object has no attribute 'cleaned_data'
Internal Server Error: /register/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 35, in register
    if form.clean_email():
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_14/solved/django_questions/library/views.py", line 20, in clean_email
    email = self.cleaned_data['email']
AttributeError: 'RegistrationForm' object has no attribute 'cleaned_data'
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog/post_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/post_detail.html
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 97, in __call__
    rendered = toolbar.render_toolbar()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 134431
Internal Server Error: /blog
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 97, in __call__
    rendered = toolbar.render_toolbar()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET /blog HTTP/1.1" 500 134467
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'djdt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/middleware.py", line 97, in __call__
    rendered = toolbar.render_toolbar()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/debug_toolbar/toolbar.py", line 84, in render_toolbar
    return render_to_string("debug_toolbar/base.html", context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'djdt' is not a registered namespace
"GET / HTTP/1.1" 500 134431
/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/django_questions/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 15862
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 16675
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 14601
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4742
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'debug_toolbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'debug_toolbar' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'debug_toolbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'debug_toolbar' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'debug_toolbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'debug_toolbar' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'debug_toolbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'debug_toolbar' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1026, in find_library
    return parser.libraries[name]
KeyError: 'debug_toolbar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shivamsri/Documents/zigsaw/django/final/question_15/solved/django_questions/library/views.py", line 7, in blog_post_detail
    return render(request, 'blog_detail.html', {'post': post})
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1088, in load
    lib = find_library(parser, name)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/template/defaulttags.py", line 1028, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'debug_toolbar' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
Internal Server Error: /events/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view library.views.event_list didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /events/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view library.views.event_list didn't return an HttpResponse object. It returned None instead.
Internal Server Error: /events/
Traceback (most recent call last):
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/Users/shivamsri/.pyenv/versions/3.8.10/lib/python3.8/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view library.views.event_list didn't return an HttpResponse object. It returned None instead.
